### ISSUE TITLE
jupiter-controller-update error

### ISSUE THREAD

**Issue by DocMAX** [ValveSoftware/SteamOS#1441]
I'm not running SteamOS but Arch Linux. Why do i get an error here?
Also Steam does not detect SteamDeck Controller anymore.
Any ideas?

Kernel: Linux steamdeck 6.8.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000 x86_64 GNU/Linux

```
root@steamdeck: ~ # jupiter-controller-update
Traceback (most recent call last):
  File "/usr/share/jupiter_controller_fw_updater/d21bootloader16.py", line 1220, in <module>
    cli()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/jupiter_controller_fw_updater/d21bootloader16.py", line 1074, in get_devices_json
    print(json.dumps(devs))
          ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BusType is not JSON serializable
!! Failed to enumerate devices

```

**Comment by DocMAX** [comment]
Yes plain Arch Linux. But why shouldn't this be supported? Anyway i updated the controllers wie SteamOS from external disk. Closed.

**Comment by RodoMa92** [comment]
Not sure why you closed it, since this will come back to bite Valve once they'll update the python base. I've tracked down the source of the error, it's an hid package regression introduced on 1.0.6 see https://github.com/ublue-os/bazzite/issues/1108 and https://github.com/apmorton/pyhidapi/issues/60. Downgrading to 1.0.5 fixes the problem entirely.
