### ISSUE TITLE
[Steam Deck] frozen on boot screen

### ISSUE THREAD

**Issue by JohnRillos** [ValveSoftware/SteamOS#868]
#### Your system information

* Steam client version: Not sure how to check this in the terminal.
* SteamOS version: 3.3.1
* Opted into Steam client beta?: I opted into the Preview channel, I believe for the Steam client.
* Opted into SteamOS beta?: Unsure, probably not.
* Have you checked for updates in Settings > System?: I just installed the Oct 4 update from the Preview channel, now I have this issue.

#### Please describe your issue in as much detail as possible:
Current issue:
When I turn my steam deck on, it plays the chime, then stays frozen on a still image of the Steam deck logo on a black background, indefinitely.

#### Steps for reproducing this issue:
Not sure if this is related, but I had previously edited my `/usr/bin/gamescope-session` file as per [this Reddit post](https://www.reddit.com/r/SteamDeck/comments/v10egz/how_to_use_1080p_resolution_on_an_external_4k/) (I added the line `-W 1920 -H 1080`). This was so that I could force the Deck to output 1080p on a 4K TV, and it has worked until now.

I was on the Beta channel, then I switched to the Preview channel today (Oct 4) to try out the update to external display resolution settings. Everything looked fine after I restarted in the Preview channel.

After I installed the update, it occurred to me that I should undo my change to `gamescope-session` since it was a workaround for an issue that this update might fix. I then switched to Desktop mode, and commented out the line I added to (`# -W 1920 -H 1080`). I then restarted the Steam deck from desktop mode.

Since then, I have had the issue I described above. When I turn my Steam Deck on, it stays frozen on the boot image.

I am able to connect with SSH, and found this in the `journalctl` output:

```
Oct 04 18:06:08 steamdeck PluginLoader[968]: [injector][DEBUG]: ClientConnectorError excepted.
Oct 04 18:06:08 steamdeck PluginLoader[968]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment...
Oct 04 18:06:08 steamdeck PluginLoader[968]: [injector][ERROR]: Traceback (most recent call last):
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "aiohttp/connector.py", line 986, in _wrap_create_connection
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "asyncio/base_events.py", line 1064, in create_connection
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "asyncio/base_events.py", line 1049, in create_connection
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "asyncio/base_events.py", line 960, in _connect_sock
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "asyncio/selector_events.py", line 500, in sock_connect
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "asyncio/selector_events.py", line 535, in _sock_connect_cb
Oct 04 18:06:08 steamdeck PluginLoader[968]: ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8080)
Oct 04 18:06:08 steamdeck PluginLoader[968]: The above exception was the direct cause of the following exception:
Oct 04 18:06:08 steamdeck PluginLoader[968]: Traceback (most recent call last):
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "injector.py", line 68, in get_tabs
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "aiohttp/client.py", line 535, in _request
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "aiohttp/connector.py", line 542, in connect
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "aiohttp/connector.py", line 907, in _create_connection
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "aiohttp/connector.py", line 1206, in _create_direct_connection
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "aiohttp/connector.py", line 1175, in _create_direct_connection
Oct 04 18:06:08 steamdeck PluginLoader[968]:   File "aiohttp/connector.py", line 992, in _wrap_create_connection
Oct 04 18:06:08 steamdeck PluginLoader[968]: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [Connect call failed ('127.0.0.1', 8080)]
```

**Comment by JohnRillos** [comment]
Update: Never mind, I got it working!

I removed my comment from `gamescope-session` and now it was able to verify the installation and boot to Steam.

PSA: don't add comments to `gamescope-session` :man_facepalming:
